</div> 
    <div class="row">
        <?php if($error != ''): ?>
            <?php foreach ?>
            <div class="alert alert-danger col-md-12 " role="alert">
                <h3>Error :</h3>
                <ul>
                    <?= $error ?>
                </ul>
            </div>
        <?php endif ?>
    </div>
<div class="col-md-10 p-0">
    <div class="card mb-3">
        <div class="card-header text-white bg-dark">User add</div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="title">Title of article</label>
                    <input type="text" class="form-control" id="title" name="title" placeholder="Title">
                </div>
                <div class="form-group">
                    <label for="subtitle">Subtitle of article</label>
                    <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Subitle">
                </div>
                <div class="form-group">
                    <label for="content">Content of article</label>
                    <textarea class="form-control" id="content" name="content" rows="3"></textarea>
                </div>
                <div class="form-group">
                    <label for="picture">Picture</label>
                    <input type="file" class="form-control" id="picture" accept="image/png, image/jpeg, image/gif, image/svg" name="picture" placeholder="your picture">
                </div> 
                <div class="form-group">
                    <label for="date">Date of article</label>
                    <input type="date" class="form-control" id="date" name="date">
                </div>
                <div class="form-group">
                    <label for="hour">Hour of article</label>
                    <input type="time" class="form-control" id="hour" name="hour">
                </div>           
                <div class="row">
                    <button type="submit" class="btn btn-primary ml-3 mt-2" name="submit">Save</button>
                </div>
                            
            </form>
        </div>
    </div>
</div>
</div>
</section>