<section class="container mb-3">
<div class="row">
        <div class="col-md-4 pl-0">
            <div class="card p-md-0 mb-3">
                <div class="card-header text-white bg-dark">Visualisation rapide</div>
                <div class="card-body">
                    <p class="card-text">Pour voir tout de suite votre site</p>
                    <button type="button" class="btn btn-primary col-12">
                        Afficher vote site
                    </button>
                </div>
            </div>
            <div class="card p-md-0 mb-3">
                <div class="card-header text-white bg-dark">Actions rapides</div>
                <div class="card-body ml-2">
                    <div class="row mb-2">
                        <a href="addArticle.php" class="card-link"><i class="far fa-newspaper"></i> Ajouter un article</a>
                    </div>
                    <div class="row mb-2">
                        <a href="#" class="card-link"><i class="far fa-file"></i> Ajouter une page</a>
                    </div>
                    <div class="row mb-2">
                        <a href="addUser.php" class="card-link"><i class="fas fa-user-alt"></i> Ajouter un utilisateur</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8 pr-0">
            <div class="card mb-3">
                <div class="card-header text-white bg-dark">Article rapide</div>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <label for="title">Titre de l'article</label>
                            <input type="text" class="form-control" id="title" name="title" placeholder="Title">
                        </div>
                        <div class="form-group">
                            <label for="content">Content of article</label>
                            <textarea class="form-control" id="content" name="content" rows="3"></textarea>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="Publish" id="Publish" value="option1">
                            <label class="form-check-label" for="Publish"> Publish</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="draft" id="draft" value="option2">
                            <label class="form-check-label" for="draft"> Draft</label>
                        </div>
                        <div class="row">
                            <button type="submit" class="btn btn-primary ml-3 mt-2">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="container">
    <div class="row">
        <div class="col-md-7 pl-0">
            <div class="card  p-md-0 ">
                <div class="card-header text-white bg-dark"><h5>Liste des derniers articles</h5></div>
                <div class="card-body p-0">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <h6>Article 1</h6>
                            <p>début du texte de l'article (...)</p>
                            <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
                        </li>
                        <li class="list-group-item">
                            <h6>Article 1</h6>
                            <p>début du texte de l'article (...)</p>
                            <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
                        </li>
                        <li class="list-group-item">
                            <h6>Article 2</h6>
                            <p>début du texte de l'article (...)</p>
                            <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
                        </li>
                        <li class="list-group-item">
                            <h6>Article 3</h6>
                            <p>début du texte de l'article (...)</p>
                            <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
                        </li>
                        <li class="list-group-item">
                            <h6>Article 4</h6>
                            <p>début du texte de l'article (...)</p>
                            <footer class="blockquote-footer">Auteur : <cite title="Source Title">Fred</cite></footer>
                        </li>
                    </ul>
                </div>
            </div>
            <a href="#" class="card-link">Voir tous les articles</a>
        </div>
        <div class="col-md-5 pr-0">
            <div class="card p-md-0">
                <div class="card-header text-white bg-dark"><h5>Liste des derniers commentaires</h5></div>
                <div class="card-body p-0">
                    <ul class="list-group">
                        <li class="list-group-item text-right">
                            <h5>Lorem ipsum dolor sit amet, consectetur (...)</h5>
                            <footer class="blockquote-footer">De <cite title="Source Title">Jean bob</cite></footer>
                        </li>
                        <li class="list-group-item text-right">
                            <h5>Lorem ipsum dolor sit amet, consectetur (...)</h5>
                            <footer class="blockquote-footer">De <cite title="Source Title">Jean bob</cite></footer>
                        </li>
                        <li class="list-group-item text-right">
                            <h5>Lorem ipsum dolor sit amet, consectetur (...)</h5>
                            <footer class="blockquote-footer">De <cite title="Source Title">Jean bob</cite></footer>
                        </li>
                        <li class="list-group-item text-right">
                            <h5>Lorem ipsum dolor sit amet, consectetur (...)</h5>
                            <footer class="blockquote-footer">De <cite title="Source Title">Jean bob</cite></footer>
                        </li>
                        <li class="list-group-item text-right">
                            <h5>Lorem ipsum dolor sit amet, consectetur (...)</h5>
                            <footer class="blockquote-footer">De <cite title="Source Title">Jean bob</cite></footer>
                        </li>
                    </ul>
                </div>
            </div>
            <a href="#" class="card-link">Voir tous les commentaires</a>
        </div>
    </div>
</section>