<section class="container mb-3">
    <div class="row">
        <div class=" col-4 p-0">
            <a href="addUser.php">
                <button type="button" class="btn btn-primary ">
                    Add article
                </button>
            </a>
        </div> 
    </div>
    <div class="row">
        <div class="col-md-12 p-0 mt-3">
            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                        <th scope="col">Titre</th>
                        <th scope="col">Catégorie</th>
                        <th scope="col">Date de publication</th>
                        <th scope="col">Auteur</th>
                        <th class="w-25" scope="col">Visuel</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($usersInfos as $userInfo) : ?>
                    <tr>
                        <td><?= $userInfo['id'] ?></td>
                        <td><?= $userInfo['first_name'] ?></td>
                        <td><?= $userInfo['last_name'] ?></td>
                        <td><?= $userInfo['created_date'] ?></td>
                        <td><?= $userInfo['email'] ?></td>
                        <td><?= $userInfo['role'] ?></td>
                        <td>
                            <a href="#"><i class="fas fa-edit"></i></a>
                            <a href="#"><i class="fas fa-trash-alt"></i></a>
                        </td>                                
                    </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>   
</section>