<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>Admin bootstrap</title>
</head>
<body>
    <header>

    </header>
    <main>
        <section class="container mb-3 mt-5 p-0">            
            <div class="row">
                <?php if($error != ''): ?>
                    <div class="alert alert-danger col-md-12 " role="alert">
                        <h3>Error :</h3>
                        <ul>
                            <?= $error ?>
                        </ul>
                    </div>
                <?php endif ?>
            </div>
                <div class="col-md-10 p-0">
                    <div class="card mb-3">
                        <div class="card-header text-white bg-dark">User login</div>
                        <div class="card-body">
                            <form method="post">
                                
                                <div>
                                    <label for="email">Email address</label>
                                    <input type="email" required class="form-control <?= $isInvalidEmail ?>" id="email" name="email" aria-describedby="emailHelp" placeholder="write your mail" value="<?= $email ?>">
                                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                                </div>
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <input type="password" required class="form-control <?= $isInvalidPassword ?>" id="password" name="password" placeholder="write your password">
                                </div>
                                <div class="row">
                                    <button type="submit" class="btn btn-primary col-md-4 ml-3 mt-4">Log in</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main> 



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>